Dev
MimiUmoh/Mini_SOM_project pull request #1
Opened 2019-02-04 16:24 UTC by MimiUmoh

2019-02-04 17:55 UTC, richgurney requested changes
Hi Emem, your commit messages need better descriptions. One word messages are not very helpful for anyone looking at what you have done. The code is looking good. Check out the readme there are a few things to improve in there. Make sure you write out a good description like I said below. This is really important for people understanding what you have written.

2019-02-04 17:55 UTC, richgurney commented on README.md
> +3.	If you have not got the json and httparty gem installed, make sure you install them by doing  gem install ‘json’ , gem install ‘httparty.’
Could we not create a Gemfile and get the user to run bundle?

2019-02-04 17:55 UTC, richgurney commented on README.md
> +3.	If you have not got the json and httparty gem installed, make sure you install them by doing  gem install ‘json’ , gem install ‘httparty.’
We dont need step 3 if you run bundle

2019-02-04 17:55 UTC, richgurney commented on spec/movie_reviews_spec.rb
> +    it 'Should be an array' do
These test descriptions are really hard to follow, you need to specify the things you expect to be something. For example '   it 'should return the thing as an data_type'

2019-02-05 09:26 UTC, MimiUmoh commented on spec/movie_reviews_spec.rb
> +    it 'Should be an array' do
Oh okay, thanks for letting me know because I was  kind of confused as to how to write it.

2019-03-05 11:54 UTC, merged